#!/usr/bin/env bash
# build-iso.sh — OPTIONAL: bake the kickstart + this repo into a Fedora 44 netinstall ISO.
#   extras/kickstart/build-iso.sh [path/to/Fedora-Everything-netinst-x86_64-44-*.iso]
# Output: build/fedora44-deploy.iso  (write it to a USB stick with Fedora Media Writer
# or `sudo dd if=build/fedora44-deploy.iso of=/dev/sdX bs=4M status=progress oflag=sync`).
# Needs: lorax (mkksiso), xorriso, pykickstart (ksvalidator) — `uvx` fallback for the latter.
set -euo pipefail
ROOT=$(cd "$(dirname "$(readlink -f "$0")")/../.." && pwd)
KSDIR="$ROOT/extras/kickstart/ks/parts"
BUILD="$ROOT/build"
CACHE=${XDG_CACHE_HOME:-$HOME/.cache}/fedora-deploy
REL=44
ISO_DIR="https://download.fedoraproject.org/pub/fedora/linux/releases/$REL/Everything/x86_64/iso"
mkdir -p "$BUILD" "$CACHE"

need() { command -v "$1" >/dev/null || { echo "missing '$1' — sudo dnf install $2"; exit 1; }; }
need mkksiso lorax
need xorriso xorriso

# ---------------------------------------------------------------- 1. kickstart
KS="$BUILD/fedora44-deploy.ks"
{
  echo "# GENERATED by scripts/build-iso.sh from extras/kickstart/ks/parts/*.ks — edit those, not this."
  echo "# built $(date -Is) from $(git -C "$ROOT" describe --always --dirty 2>/dev/null || echo 'uncommitted tree')"
  for p in "$KSDIR"/*.ks; do printf '\n# ----- %s\n' "$(basename "$p")"; cat "$p"; done
} > "$KS"
if command -v ksvalidator >/dev/null; then KSV=(ksvalidator)
else KSV=(uvx --quiet --from pykickstart ksvalidator); fi
echo "==> validating kickstart (F$REL)"
"${KSV[@]}" -v "F$REL" "$KS"

# ---------------------------------------------------------------- 2. base ISO
ISO=${1:-}
if [ -z "$ISO" ]; then
  name=$(curl -fsSL "$ISO_DIR/" | grep -oE "Fedora-Everything-netinst-x86_64-$REL-[0-9.]+\.iso" | sort -uV | tail -1)
  sum=$(curl -fsSL "$ISO_DIR/" | grep -oE "Fedora-Everything-$REL-[0-9.]+-x86_64-CHECKSUM" | sort -uV | tail -1)
  ISO="$CACHE/$name"
  [ -f "$ISO" ] || { echo "==> downloading $name"; curl -fL --progress-bar -o "$ISO.part" "$ISO_DIR/$name" && mv "$ISO.part" "$ISO"; }
  echo "==> verifying checksum"
  curl -fsSL -o "$CACHE/$sum" "$ISO_DIR/$sum"
  curl -fsSL -o "$CACHE/fedora.gpg" https://fedoraproject.org/fedora.gpg
  if command -v gpgv >/dev/null; then gpgv --keyring "$CACHE/fedora.gpg" "$CACHE/$sum"; fi
  ( cd "$CACHE" && sha256sum --ignore-missing -c "$sum" )
fi

# ---------------------------------------------------------------- 3. payload
STAGE="$BUILD/stage/fedora-deploy"
rm -rf "$BUILD/stage"; mkdir -p "$STAGE"
rsync -a --exclude .git --exclude build --exclude '__pycache__' --exclude node_modules "$ROOT/" "$STAGE/"

# ---------------------------------------------------------------- 4. bake
OUT="$BUILD/fedora44-deploy.iso"
rm -f "$OUT"
echo "==> mkksiso"
mkksiso --ks "$KS" --add "$STAGE" ${EXTRA_KARGS:+-c "$EXTRA_KARGS"} "$ISO" "$OUT"
( cd "$BUILD" && sha256sum "$(basename "$OUT")" > "$(basename "$OUT").sha256" )
ls -lh "$OUT"
cat <<EOF

Done. Boot the USB; the kickstart runs automatically.
  * Force a specific target disk: EXTRA_KARGS="inst.deploy.disk=nvme0n1" $0
  * Anaconda stops at the summary: create your user, CHECK the disk, Begin Installation.
EOF
