# fedora-deploy — Fedora 44 KDE Plasma
# Graphical install. Everything is preset EXCEPT the user account, so Anaconda
# stops on the summary screen: create your user there, check the disk shown under
# "Installation Destination", then press Begin Installation.
graphical
lang en_US.UTF-8
keyboard --vckeymap=us --xlayouts='us'
timezone America/Chicago --utc
network --bootproto=dhcp --device=link --activate --onboot=on

url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-44&arch=x86_64"
repo --name=updates --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f44&arch=x86_64"

selinux --enforcing
firewall --enabled --service=mdns
firstboot --disable
bootloader --timeout=3
# (no rootpw / user lines on purpose — Anaconda asks on every machine)

# Storage is generated by %pre (see 10-pre-disk.ks). If it could not pick a disk
# safely, the file is empty and Anaconda asks you to choose.
%include /tmp/part.ks
